// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCPhxvBm9FYfXYl4BM9uQtwD6mOfxJ0bTQ',
    appId: '1:554230510889:web:da958537f59fd432',
    messagingSenderId: '554230510889',
    projectId: 'project-709169105452228959',
    authDomain: 'project-709169105452228959.firebaseapp.com',
    databaseURL: 'https://project-709169105452228959.firebaseio.com',
    storageBucket: 'project-709169105452228959.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDtno1hJvhnczEAt_AIenNF-a7ZhOyW4iw',
    appId: '1:554230510889:android:f232329fcf55839b8b7338',
    messagingSenderId: '554230510889',
    projectId: 'project-709169105452228959',
    databaseURL: 'https://project-709169105452228959.firebaseio.com',
    storageBucket: 'project-709169105452228959.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCEr7epwGg9IwzcHbZHjzLW-tQjKmL6gnM',
    appId: '1:554230510889:ios:ffb9c03f280ff5a08b7338',
    messagingSenderId: '554230510889',
    projectId: 'project-709169105452228959',
    databaseURL: 'https://project-709169105452228959.firebaseio.com',
    storageBucket: 'project-709169105452228959.appspot.com',
    iosClientId: '554230510889-p3mkmoui3ojbvn7g483blmfltc5dfh1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlameFirebase',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCEr7epwGg9IwzcHbZHjzLW-tQjKmL6gnM',
    appId: '1:554230510889:ios:ffb9c03f280ff5a08b7338',
    messagingSenderId: '554230510889',
    projectId: 'project-709169105452228959',
    databaseURL: 'https://project-709169105452228959.firebaseio.com',
    storageBucket: 'project-709169105452228959.appspot.com',
    iosClientId: '554230510889-p3mkmoui3ojbvn7g483blmfltc5dfh1t.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFlameFirebase',
  );
}
